---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
  labels:
    name: catalogue-db
    type: database
    clustername: kind-workertype3
    region: eu-west-1
spec:
  ports:
    # the port that this service should serve on
  - port: 3306
    targetPort: 3306
  selector:
    name: catalogue-db
    type: database
    clustername: kind-workertype3
    region: eu-west-1
