---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
    type: database
    clustername: kind-workertype3
    region: eu-west-1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30001
  selector:
    name: front-end
    type: database
    clustername: kind-workertype3
    region: eu-west-1
