---
apiVersion: v1
kind: Service
metadata:
  name: queue-master
  labels:
    name: queue-master
    type: database
    clustername: kind-workertype3
    region: eu-west-1
  annotations:
    prometheus.io/path: "/prometheus"
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: queue-master
    type: database
    clustername: kind-workertype3
    region: eu-west-1
