---
apiVersion: v1
kind: Service
metadata:
  name: session-db
  labels:
    name: session-db
    type: database
    clustername: kind-workertype3
    region: eu-west-1
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    name: session-db
    type: database
    clustername: kind-workertype3
    region: eu-west-1
