---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  labels:
    name: user-db
    type: database
    clustername: kind-workertype3
    region: eu-west-1
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: user-db
    type: database
    clustername: kind-workertype3
    region: eu-west-1
