---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    name: user-db
    type: database
    clustername: kind-workertype3
    region: eu-west-1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-db
      type: database
      clustername: kind-workertype3
      region: eu-west-1
  template:
    metadata:
      labels:
        name: user-db
        type: database
        clustername: kind-workertype3
        region: eu-west-1
    spec:
      containers:
      - name: user-db
        image: weaveworksdemos/user-db:0.3.0

        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
