---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    name: user
    type: database
    clustername: kind-workertype3
    region: eu-west-1
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: user
    type: database
    clustername: kind-workertype3
    region: eu-west-1

